#!/usr/bin/env python
import urllib2
import json
import sys
import urllib

data = {}
data['public'] = False
data['files'] = {}
if len(sys.argv) == 1:
  data['files']['gist.txt'] = {'content': sys.stdin.read()}
else:
  for f in sys.argv[1:]:
    fh = open(f, 'r')
    data['files'][f] = {'content': fh.read()}
    fh.close()
req = urllib2.Request(
    "https://api.github.com/gists",
    json.dumps(data),
    {'Content-Type': 'application/x-www-form-urlencoded'},
)

try:
  response = json.load(urllib2.urlopen(req))
except urllib2.HTTPError, e:
  print e, e.read()
print response['html_url']
